#!/usr/bin/env bash

#exit immediately if any command returns a non zero digit or fails
set -e

#files destination
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove the folder if it already exists
rm -r $OUTPUT_DIR

#output folder
mkdir -p $OUTPUT_DIR

#generate random number of files
NUM_FILES=$((RANDOM % 6 + 5))

for ((i = 1; i <= NUM_FILES; i++)); do
    # Generate a random file name
    FILE_NAME="file_$i.txt"
    
    # Determine random file size between 1KB and 10KB
    FILE_SIZE=$((RANDOM % 10 + 1))K
    
    # Create the file with random content
    head -c "$FILE_SIZE" /dev/urandom > "$OUTPUT_DIR/$FILE_NAME"

    echo "Created $FILE_NAME of size $FILE_SIZE"
done
