#!/usr/bin/env bash

echo "put-object"

###Check for bucket name
if [ -z "$1" ]; then
    echo "Bucket name required. Error. e.g../bucket my-bucket-name"
    exit 1
fi

#check for filename

if [ -z "$2" ]; then
    echo "Filename prefix required. Error. . e.g../bucket my-bucket-name my-filename-prefix"
    exit 1
fi 

BUCKET_NAME=$1
FILENAME=$2

filename_with_ext=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $filename_with_ext

