#!/usr/bin/env bash

echo "== sync"
#exit immediately if any command returns a non zero digit or fails
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "Bucket name required. Error. e.g../bucket my-bucket-name"
    exit 1
fi

#check for filename prefix

if [ -z "$2" ]; then
    echo "Filename prefix required. Error. . e.g../bucket my-bucket-name my-filename-prefix"
    exit 1
fi 

BUCKET_NAME=$1
FILENAME_PREFIX=$2
#files destination
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove the folder if it already exists
rm -r $OUTPUT_DIR

#output folder
mkdir -p $OUTPUT_DIR

#generate random number of files
NUM_FILES=$((RANDOM % 6 + 5))

for ((i = 1; i <= NUM_FILES; i++)); do
    # Generate a random file name
    FILE_NAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
    
    ### Determine random file size between 1KB and 10KB
    FILE_SIZE=$((RANDOM % 10 + 1))K
    
    # Create the file with random content
    head -c "$FILE_SIZE" /dev/urandom > "$FILE_NAME"

    echo "Created $FILE_NAME of size $FILE_SIZE"
done

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME