#!/usr/bin/env bash

echo "== deploy sns"

STACK_NAME="sns-basic"

aws cloudformation deploy \
--template-file template.yaml \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-2